main = ".worker-next/index.mjs"
name = "hok-opener"
compatibility_date = "2024-11-02"
compatibility_flags = ["nodejs_compat"]
experimental_assets = { directory = ".worker-next/assets", binding = "ASSETS" }